model_name: lightgbm
model_type: lightgbm_classifier

params:
  num_leaves: 31
  max_depth: 4
  learning_rate: 0.03
  n_estimators: 500
  min_child_samples: 100
  subsample: 0.8
  colsample_bytree: 0.8
  verbose: -1

early_stopping_rounds: 50
standardize: false
